FROM rust:1.31-slim

LABEL "com.github.actions.name"="Cargo Test"
LABEL "com.github.actions.description"="Run all application tests using the Cargo build tool"
LABEL "com.github.actions.icon"="clipboard"
LABEL "com.github.actions.color"="orange"

LABEL "repository"="https://github.com/irishshagua/zDrinks-CLI"
LABEL "homepage"="https://irishshagua.github.io/"
LABEL "maintainer"="Brian Mooney <brian_satchwannabe@hotmail.com>"
